### ISSUE TITLE
Search dropdown in wrong place

### ISSUE THREAD

**Issue by GaryJones** [Yago/Cortana#22]
When the styles being documented are not based on Bootstrap, then the Cortana core styles are missing a `.dropdown-menu { position: absolute; }` which is needed to keep the search results in the right place. Without this, the search results appear on the left, and push down the rest of the content.

**Comment by hkutcher** [comment]
Adding this to the CSS did not resolve the issue for me. Played around with the CSS, recompiled hologram, cleared cache, refreshed, nada. Anyone fixed this?

**Comment by GaryJones** [comment]
~~~css
.dropdown-menu.ng-isolate-scope {
	position: absolute;
}
~~~
... is what I have in the bottom of my project style.scss so that Hologram sees it.
