### ISSUE TITLE
Arabic Texts are not rendering properly.

### ISSUE THREAD

**Issue by abrahamjagadeesh** [Yago/Cortana#31]
![image](https://cloud.githubusercontent.com/assets/6632159/6544933/4c8de442-c580-11e4-9814-36edf2eeb63f.png)

**Comment by tonifisler** [comment]
Try removing `@charset "UTF-8";` at the top of your .scss file, I'm guessing this is the issue here.

**Comment by abrahamjagadeesh** [comment]
Great! works now. thanks.
