### ISSUE TITLE
Running hologram with cortana theme issue

### ISSUE THREAD

**Issue by kkashou** [Yago/Cortana#32]
Everytime I run the command for hologram with grunt I get this error:

<pre>
Custom markdown renderer Cortanamarkdownrenderer loaded.
Adding renderer for haml examples
Adding renderer for html examples
Adding renderer for js examples
Adding renderer for jsx examples
Adding renderer for react examples
Adding renderer for slim examples
(erb):32:in `block in get_binding': undefined method `split' for nil:NilClass (NoMethodError)
	from (erb):31:in `each'
	from (erb):31:in `get_binding'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:243:in `write_page'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:199:in `block in write_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:185:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:185:in `write_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:147:in `build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:87:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/cli.rb:38:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/cli.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/bin/hologram:6:in `<top (required)>'
	from /usr/bin/hologram:23:in `load'
	from /usr/bin/hologram:23:in `<main>'

</pre>

Has anyone come across this issue before?

**Comment by kkashou** [comment]
I just switch back to hologram 1.3.1 and it worked.

**Comment by GaryJones** [comment]
Seems to be an issue with the `index:` line in the config. Disable that, and just include an `index.md` file in the source directory.
